version: '3.5'

networks:
    laravel_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.1.0/24

services:

    # apache
    web:
        container_name: ${COMPOSE_PROJECT_NAME}_web
        build: ./apache
        ports:
            - "${WEB_HTTP_PORT}:80"
            - "${WEB_SSL_PORT}:443"
        volumes:
            - ../src:/var/www/vhosts
            - ./apache/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
        depends_on:
            - app
        networks:
            - laravel_net

    # app
    app:
        container_name: ${COMPOSE_PROJECT_NAME}_app
        build:
            context: ./php-fpm
            args:
                - PHPFPM_VERSION=${PHPFPM_VERSION}
                - COMPOSER_VERSION=${COMPOSER_VERSION}
                - NODEJS_VERSION_MAJOR=${NODEJS_VERSION_MAJOR}
        ports:
            - "${VITE_PORT}:5173"
        volumes:
            - ../src:/var/www/vhosts
        depends_on:
            - db
            - redis
        networks:
            - laravel_net

    # db
    db:
        container_name: ${COMPOSE_PROJECT_NAME}_db
        build:
            context: ./mariadb
            args:
                - MARIADB_VERSION=${MARIADB_VERSION}
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - db-store:/var/lib/mysql
            - ./mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - laravel_net

    # mail
    mailhog:
        container_name: ${COMPOSE_PROJECT_NAME}_mail
        build: ./mailhog
        ports:
            - ${MAIL_SMTP_PORT}:1025
            - ${MAIL_WEB_PORT}:8025
        volumes:
            - mail-store:/tmp
        environment:
            MH_STORAGE: maildir
            MH_MAILDIR_PATH: /tmp
        networks:
            - laravel_net

    # redis
    redis:
        container_name: ${COMPOSE_PROJECT_NAME}_redis
        build:
            context: ./redis
            args:
                - REDIS_VERSION=${REDIS_VERSION}
        # command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - "${REDIS_PORT}:6379"
        volumes:
            - redis-store:/data
        # environment:
        #     - REDIS_PASSWORD=${REDIS_PASSWORD}
        networks:
            - laravel_net

volumes:
    db-store:
        name: ${COMPOSE_PROJECT_NAME}_db_store
    mail-store:
        name: ${COMPOSE_PROJECT_NAME}_mail_store
    redis-store:
        name: ${COMPOSE_PROJECT_NAME}_redis_store
